import { PtBadge } from './ui/PtBadge';
import { Icon } from './ui/Icon';
import { useAppStore, type TradeSignal } from '@/stores';

function timeAgo(ts: number): string {
  const s = Math.floor((Date.now() - ts) / 1000);
  if (s < 60) return `${s}s ago`;
  if (s < 3600) return `${Math.floor(s / 60)}m ago`;
  if (s < 86400) return `${Math.floor(s / 3600)}h ago`;
  return `${Math.floor(s / 86400)}d ago`;
}

function fmtCurrency(n: number): string {
  return (n < 0 ? '-' : '') + '$' + Math.abs(n).toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 });
}

interface SignalRowProps {
  signal: TradeSignal;
  isNew: boolean;
}

function SignalRow({ signal, isNew }: SignalRowProps) {
  const statusVariant = {
    executed: 'success',
    pending:  'warning',
    failed:   'danger',
    skipped:  'default',
  } as const;

  return (
    <div
      className={isNew ? 'pt-slide-in' : ''}
      style={{
        display: 'flex', alignItems: 'center', gap: 12, padding: '10px 8px',
        borderBottom: '1px solid var(--pt-border)',
        animation: isNew ? 'pt-signal-flash 1s ease' : 'none',
      }}
    >
      {/* Avatar */}
      <div style={{
        width: 32, height: 32, borderRadius: 8,
        background: 'var(--pt-surface-2)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        fontSize: 11, fontWeight: 700, color: 'var(--pt-text-2)', flexShrink: 0,
      }}>
        {(signal.trader?.userName || 'UN').slice(0, 2).toUpperCase()}
      </div>

      {/* Info */}
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 2, flexWrap: 'wrap' }}>
          <span style={{ fontWeight: 600, fontSize: 12 }}>{signal.trader?.userName || 'Unknown'}</span>
          <PtBadge variant={signal.side === 'BUY' ? 'buy' : 'sell'}>{signal.side}</PtBadge>
          <PtBadge variant={statusVariant[signal.status]}>{signal.status}</PtBadge>
        </div>
        <div style={{ fontSize: 12, color: 'var(--pt-text-3)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
          {signal.market?.question?.slice(0, 40) ?? signal.market?.id ?? '—'}
          {(signal.market?.question?.length ?? 0) > 40 ? '…' : ''}
        </div>
      </div>

      {/* Amount + time */}
      <div style={{ textAlign: 'right', flexShrink: 0 }}>
        <div style={{ fontFamily: 'var(--pt-mono)', fontSize: 13, fontWeight: 600 }}>
          {fmtCurrency(signal.size)}
        </div>
        <div style={{ fontSize: 11, color: 'var(--pt-text-3)' }}>
          {timeAgo(signal.timestamp)}
        </div>
      </div>
    </div>
  );
}

interface ActivityFeedProps {
  /** Pass extra live signals generated by the agent in real-time */
  extraSignals?: TradeSignal[];
}

export function ActivityFeed({ extraSignals = [] }: ActivityFeedProps) {
  const { tradeSignals } = useAppStore();
  const all = [...extraSignals, ...tradeSignals].slice(0, 30);

  return (
    <div style={{ background: 'var(--pt-surface-1)', border: '1px solid var(--pt-border)', borderRadius: 12, overflow: 'hidden', height: '100%' }}>
      {/* Header */}
      <div style={{
        padding: '16px 20px', borderBottom: '1px solid var(--pt-border)',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Icon name="activity" size={16} />
          <span style={{ fontWeight: 600, fontSize: 14 }}>Live Activity</span>
        </div>
        <span style={{ fontSize: 11, color: 'var(--pt-text-3)', fontFamily: 'var(--pt-mono)' }}>
          {all.length} signals
        </span>
      </div>

      {/* Feed */}
      <div style={{ maxHeight: 480, overflowY: 'auto', padding: '8px 12px' }}>
        {all.length === 0 ? (
          <div style={{ padding: 32, textAlign: 'center', color: 'var(--pt-text-3)' }}>
            <Icon name="activity" size={28} />
            <p style={{ marginTop: 8, fontSize: 13 }}>No signals yet — follow traders to start</p>
          </div>
        ) : (
          all.map((s, i) => <SignalRow key={s.id} signal={s} isNew={i === 0} />)
        )}
      </div>
    </div>
  );
}
